f = open('instru_opcode_encode_table.dat','r')
f2 = open('instru_opcode_encode_table.h','w')
f2.write("struct instruction_opcode_encode{\n")
f2.write("  char *op_en;\n")
f2.write("  char *op1;\n")
f2.write("  char *op2;\n")
f2.write("};\n")
f2.write("typedef struct instruction_opcode_encode instruction_opcode_encode;\n")
l = f.readlines()
token1 = map(lambda x:x.split(),l)
token2 = map(lambda x: map(lambda y:(y.replace('[',']')).strip(']'),x),token1)
f2.write("#define MAX_INSTRU_OP_EN_COUNT %d\n" %len(token2))
f2.write("instruction_opcode_encode instru_op_en[MAX_INSTRU_OP_EN_COUNT] = {")
for i in range(0,len(token2)-1):
     f2.write("{\""+token2[i][0]+"\",\""+token2[i][1]+"\",\""+token2[i][2]+"\"},")
f2.write("{\""+token2[len(token2)-1][0]+"\",\""+token2[len(token2)-1][1]+"\",\""+token2[len(token2)-1][2]+"\"}};")
